### ISSUE TITLE
💥 [DevOps] Webapp: Diverse Depricated Warnings if we Run `yarn dev`

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#7763] opened 2024-08-29 11:11 UTC
## 💥 DevOps ticket

We get diverse depricated warnings if we run `yarn dev` locally, see below and diverse similar one:

```bash
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($size, 2) or calc($size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

     ╷
1157 │     padding-top: $size / 2 - 2;
     │                  ^^^^^^^^^
     ╵
    components/Badges.vue 1157:18  root stylesheet
```

**Comment by mahula** [comment] 2024-10-29 15:54
This issue can be closed as a duplicate of [#7340](https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/7340) fixed by #7988.

**Closed by mahula** 2024-10-29 15:54 UTC
Labels: good first issue, service: webapp, devops
