### ISSUE TITLE
🐛 [Bug] Search doesn't find user names with few characters

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#2800] opened 2020-10-05 12:58 UTC
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-01-16T11:24:37Z" title="Thursday, January 16th 2020, 12:24:37 pm +01:00">Jan 16, 2020</time>_

---

## :bug: Bugreport

Search doesn't find user names ("slugs") with two characters.

Example:
![hc-bug-seach-doesnt-find-slugs-less-than-two-characters-example-new](https://user-images.githubusercontent.com/17728384/72520890-b4d08d00-385a-11ea-9096-63e1bd0f9906.png)

### Steps to reproduce the behavior
1. In the search field, type in a user name of less than three characters. 
2. The search doesn't show any results.

### Expected behavior

The search results should show those users.

### Version & Environment
 Type: [any]      
 - OS: [any]      
 - Browser: [any] 
 - Version [any]  
 - Device: []  

### Additional context

If user names of two characters are permitted the search should allow for two characters, too. 
Alternative: Change user names policy i.e. mininum three characters instead of two.

Similar issue with hashtags #2635

**Comment by Tirokk** [comment] 2020-10-07 08:26
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-02-06T21:56:49Z" title="Thursday, February 6th 2020, 10:56:49 pm +01:00">Feb 6, 2020</time>_

---


Until now, we do not trigger a search if the search string is less than three characters. If we did so, we would have a lot of ugly side effects, as can be seen in #2799 
The only idea I have, to get this fixed in the case for users is, that you must search explicitly for users to skip the three characters minimum rule, This could be done by starting the search string with an '@' Symbol.
In this case, you would have to search for `@tj` to get an result.
What do you think about this solution?

**Comment by Tirokk** [comment] 2020-10-07 08:27
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-02-07T19:21:14Z" title="Friday, February 7th 2020, 8:21:14 pm +01:00">Feb 7, 2020</time>_

---


Title changed because user @"mid"  (three characters) can't be mentioned too.

**Comment by Tirokk** [comment] 2020-10-07 08:27
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-02-07T19:32:48Z" title="Friday, February 7th 2020, 8:32:48 pm +01:00">Feb 7, 2020</time>_

---


@Mogge I like your suggestion. Will it find users with a one character user name such as @_ too?

**Comment by Tirokk** [comment] 2020-10-07 10:55
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-03-24T13:47:32Z" title="Tuesday, March 24th 2020, 2:47:32 pm +01:00">Mar 24, 2020</time>_

---


Soon we will have a search result page. This page can be reached by pressing enter in the search field. After pressing enter the search is triggered independently of the length of the input. This should fix the problem.

**Comment by Tirokk** [comment] 2020-10-07 10:55
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-03-24T14:22:29Z" title="Tuesday, March 24th 2020, 3:22:29 pm +01:00">Mar 24, 2020</time>_

---


@Mogge Thank you. Is the search result page going to replace the current limited seach result preview or is it additionally?

**Comment by Tirokk** [comment] 2020-10-07 10:55
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-03-24T15:18:30Z" title="Tuesday, March 24th 2020, 4:18:30 pm +01:00">Mar 24, 2020</time>_

---


It is additionally. When you press enter, you will see a page showing the results of the search more detailed as in the drop down. Also there are shown more results than just five for each type as it is now. The work on this page is in progressed, planned to be deployed in two weeks to production.

**Comment by Tirokk** [comment] 2020-10-07 10:55
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-03-24T17:46:08Z" title="Tuesday, March 24th 2020, 6:46:08 pm +01:00">Mar 24, 2020</time>_

---


@Mogge So the results on the preview and the first results of the views of the results page are identical (except that the results page contains more details)? In other words, no more limitation for the length of the input for the preview?

**Comment by Tirokk** [comment] 2020-10-07 11:01
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-03-27T13:20:05Z" title="Friday, March 27th 2020, 2:20:05 pm +01:00">Mar 27, 2020</time>_

---


No. If you press enter, the search triggers no matter how many characters are in the search box. When not pressing enter, the search triggers after having an input of at least 3 chars.
You can find user @tj now, when typing tj and press enter:
![image](https://user-images.githubusercontent.com/15882241/77760030-0608b400-7036-11ea-9c8e-792d5c28da6a.png)

**Comment by Tirokk** [comment] 2020-10-07 11:03
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-03-27T13:20:05Z" title="Friday, March 27th 2020, 2:20:05 pm +01:00">Mar 27, 2020</time>_

---


No. If you press enter, the search triggers no matter how many characters are in the search box. When not pressing enter, the search triggers after having an input of at least 3 chars.
You can find user @tj now, when typing tj and press enter:
![image](https://user-images.githubusercontent.com/15882241/77760030-0608b400-7036-11ea-9c8e-792d5c28da6a.png)

**Comment by Tirokk** [comment] 2020-10-07 11:03
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-03-27T15:15:57Z" title="Friday, March 27th 2020, 4:15:57 pm +01:00">Mar 27, 2020</time>_

---


@Mogge Thanks. I tried to search for user "tj" and it worked. 

The search function seems to work now for usernames that only consist of letters but it's inconsistent with those containing numbers or special characters:

Examples:
- "_" → hitting Enter still doesn't show the search result list
- "_michael" → _ to _mi + Enter doesn't trigger search result list, but listed with _mic and more
- "12c" → user not listed with 1 or 12, but listed with 12c
- "360" → user not listed
- "420" → not listed with 4 or 42, but listed with 420
- "4915255184321" → not listed with 4 to 491, but listed with 4915 and more
- "3lvis" → not listed with 3, 3l, 3lv, but listed with 3liv or 3livs
- "360fun" → not listed with 3 to 360, but listed with 360f to 360fun
- "911-gzm" → listed with 9 to 911-gzm
- "a_drian" → a to a_d + Enter doesn't trigger search result list, but listed with a_dr and more
- "bee-skywalker" → not listed with bee-s to bee-skywalk, but listed with bee-skywalker or skyw

Please re-check.

**Comment by Tirokk** [comment] 2020-12-10 13:02
Is this related to #2635 ?

**Comment by Mogge** [comment] 2020-12-14 07:46
I cannot see a relation to #2635 
Can we close this issue?

**Comment by ulfgebhardt** [comment] 2020-12-14 09:33
is the bug of this ticket resolved?

**Comment by Mogge** [comment] 2020-12-14 09:39
It is not a bug. The search in the quick search field starts, when there are at least three characters in the input field. To force the search, you can press enter. Then the user appears, even if the slug contains only one char (we had a user with the slug `_`, and you could find him/her by pressing enter).
There is a huge PR (nearly finished, just missing a test for the stupid vue-count feature) related to searches (https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/3271) which will change the behaviour of the search field.

**Comment by Mogge** [comment] 2020-12-14 09:47
Sorry. I have not seen the other points listed by @sushidave so far
I assume, that ones we merge #3271 the problems mentioned in the list should be fixed, but it should be tested. So please do not close the issue, but do not work on it until #3271 is merged.

**Closed** 2021-01-28 19:00 UTC
Labels: Github Import, bug, features:mention, good first issue
