### ISSUE TITLE
🚀 [Feature] Manifest on Website

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4027] opened 2020-11-30 10:50 UTC
## :rocket: Feature

Manifest on Website `ocelot.social`

__english__
> We want to develop the european way of doing Internet. Free, opensource, transparent, donation funded, collaboratively, decentralized, adaptive, peaceful & fulfilling.
> We started with a social Network to promote this idea and allow everyone to participate in this process. 

__german__
>Wir wollen die europäische Art, das Internet zu nutzen, weiterentwickeln. Frei, quelloffen, transparent, spendenfinanziert, gemeinschaftlich, dezentralisiert, anpassungsfähig, friedlich & erfüllend.
Wir haben mit einem sozialen Netzwerk begonnen, um diese Idee zu fördern und allen die Möglichkeit zu geben, an diesem Prozess teilzunehmen.

ISSUES in  https://github.com/Ocelot-Social-Community/website-ocelot.social

**Comment by ulfgebhardt** [comment] 2020-11-30 10:50
@Mogge

**Comment by Mogge** [comment] 2020-11-30 10:52
Why the `european` way. May be:
`We want to develop our way of doing Internet. `

**Comment by ulfgebhardt** [comment] 2020-11-30 11:56
the idea is that we europeans are trapped between America & China and dont have our own solution - "our way" reduces the geopolitical impact of the statement - but i am fine with whatever ;) @Mogge

**Comment by Mogge** [comment] 2020-11-30 12:24
I agree and I remember that I brought this up. We should discuss this in detail and how to communicate it.

**Comment by ogerly** [comment] 2020-12-01 11:57
the problem is moved to : https://github.com/Ocelot-Social-Community/website-ocelot.social/issues/7

close this

**Closed by ogerly** 2020-12-01 11:57 UTC
Labels: feature
