### ISSUE TITLE
🐛 [Bug] Yunite – On Mobile The Header Logo Click Does Not Link To Extern Page

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5550] opened 2022-10-23 15:23 UTC
## 🐛 Bugreport

Yunit:

- On mobile the header logo click does not link to extern page.
- On deskotop it works.
- Make both logo clicks configurable if they should open in a different tab respectively window.

**Comment by adrianrojek** [comment] 2022-10-24 07:11
Hey, I would like to help with this issue. Can you assign it to me ?

**Comment by Tirokk** [comment] 2022-10-24 08:31
Hey @adrianrojek ,

yes for sure you can help. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Please don’t compare from your fork to this repository, in case, because the publish action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉

I added an additional configuration wish to this issue.
Hope that's okay?

⚠️ Because this issue is part of our beta test on http://stage.yunite.me of our new network http://yunite.me in this week we need this latest in kind of two days.
Is this possible?
If not please have a look if you find an other issue.

And if you are eager you could care for kind of similar issue #5545 as well?
Please let me know if you do! ⚠️

**Comment by adrianrojek** [comment] 2022-10-24 09:05
Thanks, I´ll do my best.

**Comment by Tirokk** [comment] 2022-10-24 09:30
> Thanks, I´ll do my best.

If you need any help – installation etc. –, please let us know.
Best on Discord.

**Comment by adrianrojek** [comment] 2022-10-25 06:35
Hey my app is up and running but I am having issues with reproducing the issue and finding the problematic header icon since the one I can see seems to work the same on both desktop and mobile. Can you please give me some more information ?
Just to be sure is this the mentioned icon ? Or am I in the wrong branch or something ?
![image](https://user-images.githubusercontent.com/55430972/197699848-ce0f0716-7b1b-4da5-ae0c-fe1bd8f05991.png)

**Comment by Tirokk** [comment] 2022-10-25 08:42
Cool that you already started: @adrianrojek 🙏🏼

The Ocelot logo in file `webapp/layouts/default.vue` is the one which is …

- … for desktop configured to route to internal page or to external URL … (lines 8–23)
- … for mobile staticly routes only to internal page (lines 111–115)

For rebranding purposes we like to have:

- both to can be confirued to route to internal page or to an external URL
- and if they are configured for an external URL then
  - … an additional configuration if the external URL should be opened in a new browser window respectively tab

**Comment by adrianrojek** [comment] 2022-10-26 08:20
Hey @Tirokk , I created a new pull request with changes from your change request, I am sorry about the fork, I forgot about the invitation you sent me.

**Comment by adrianrojek** [comment] 2022-10-26 09:02
Hi, I see that I was unassigned. Is there a problem ?

**Comment by Tirokk** [comment] 2022-10-26 09:07
I reverted it.
That was accidentally by my college in the meeting.

**Closed** 2022-10-26 13:16 UTC
Labels: bug, good first issue, frontend, Yunite
